 <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Curriculum</title>
	<link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
  <link href="css/buscar.css" rel="stylesheet" media="screen">
 <style type="text/css">
 body{
   background-color:#f5f5f5
 }
 </style>
 
</head>
<body>
	
<div class="navbar">
              <div class="navbar-inner">
                <div class="container">
                  <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </a>
                  <a class="brand" href="home.php">Curriculum</a>
                  <div class="nav-collapse collapse navbar-responsive-collapse">
                    <ul class="nav">
                      
                      
                    </ul>
                    <form class="navbar-search pull-center" action="">
                      <!--comienza la busqueda-->
                      <input type="text" class="search-query span2" id="buscarpalabra" placeholder="Buscar">
                      
                       <!--termina la busqueda-->
                    </form>
                    
                    <ul class="nav pull-right">
                      
                      <li class="divider-vertical"></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Configuracion <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="crear.php">Crear</a></li>
                          
                          <li class="divider"></li>
                          
                          <li ><a href="?q=logout"><i class='icon-off' ></i>Salir</a></li>
                        </ul>
                      </li>
                    </ul>
                  </div><!-- /.nav-collapse -->
                </div>
              </div><!-- /navbar-inner -->
            </div>